//! Content Generation Agent
//!
//! This agent generates document content using Markdown templates and context
//! from the Research Agent. It resolves variables from multiple sources and
//! produces the initial Markdown document.

use crate::agents::research::ResearchContext;
use crate::agents::AgentError;
use crate::templates::TemplateEngine;
use crate::graphrag::KnowledgeGraph;
use chrono::{DateTime, Utc};
use iou_core::document::{DocumentRequest, Template, TemplateVariable, VariableSource};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use uuid::Uuid;

/// Content generation result
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeneratedDocument {
    /// Document identifier
    pub document_id: Uuid,

    /// Generated Markdown content
    pub content: String,

    /// Template variables used (for audit trail)
    pub variables: Vec<TemplateVariable>,

    /// Entity links inserted (from knowledge graph)
    pub entity_links: Vec<EntityLink>,

    /// Metadata about generated sections
    pub sections: Vec<SectionMetadata>,

    /// Generation timestamp
    pub generated_at: DateTime<Utc>,
}

/// Entity link from knowledge graph
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EntityLink {
    /// Entity ID
    pub entity_id: String,

    /// Display text in document
    pub display_text: String,

    /// Entity type (e.g., "Person", "Organization", "Location")
    pub entity_type: String,

    /// Position in document (character offset)
    pub position: usize,
}

/// Metadata about a generated section
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SectionMetadata {
    /// Section identifier
    pub name: String,

    /// Whether section was rendered
    pub rendered: bool,

    /// Content length (characters)
    pub length: usize,

    /// Whether section was auto-generated by AI
    pub ai_generated: bool,
}

/// Content generation configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContentAgentConfig {
    /// Maximum length for AI-generated sections
    pub max_section_length: usize,

    /// Whether to enable entity linking
    pub enable_entity_linking: bool,

    /// Default language for content
    pub default_language: String,

    /// Whether to use AI for content generation
    pub enable_ai_generation: bool,
}

impl Default for ContentAgentConfig {
    fn default() -> Self {
        Self {
            max_section_length: 5000,
            enable_entity_linking: true,
            default_language: "nl".to_string(),
            enable_ai_generation: false,  // Disabled by default until AI provider is configured
        }
    }
}

/// Execute the Content Generation Agent
///
/// # Arguments
/// * `request` - Original document request
/// * `research` - Research context from Research Agent
/// * `template` - Template to use for generation
/// * `kg_client` - Knowledge graph for entity resolution
/// * `engine` - Template engine for rendering
///
/// # Returns
/// Generated document with Markdown content
pub async fn execute_content_agent(
    request: &DocumentRequest,
    research: &ResearchContext,
    template: &Template,
    kg_client: &KnowledgeGraph,
    engine: &TemplateEngine,
) -> Result<GeneratedDocument, AgentError> {
    let config = ContentAgentConfig::default();
    execute_content_agent_with_config(request, research, template, kg_client, engine, &config).await
}

/// Execute the Content Generation Agent with custom configuration
pub async fn execute_content_agent_with_config(
    request: &DocumentRequest,
    research: &ResearchContext,
    template: &Template,
    _kg_client: &KnowledgeGraph,
    engine: &TemplateEngine,
    config: &ContentAgentConfig,
) -> Result<GeneratedDocument, AgentError> {
    // Step 1: Resolve all template variables from available sources
    let variables = resolve_variables(
        request,
        research,
        template,
    )?;

    // Step 2: Build template context for rendering
    let mut context = build_template_context(&variables);

    // Step 3: Add conditional section flags
    add_conditional_sections(&mut context, research, template);

    // Step 4: Generate AI-powered content sections (if enabled)
    if config.enable_ai_generation {
        generate_ai_sections(&mut context, research, config).await?;
    }

    // Step 5: Render the template
    let variables_map = variables_to_map(&variables);
    let rendered = engine.render(&template.id, &variables_map)
        .map_err(|e| AgentError::TemplateError(e.to_string()))?;

    let content = rendered.content;

    // Step 6: Extract entity links (stub for now)
    let entity_links = if config.enable_entity_linking {
        // TODO: Implement entity linking once NER is integrated
        Vec::new()
    } else {
        Vec::new()
    };

    // Step 7: Build section metadata
    let sections = extract_section_metadata(&content, template);

    Ok(GeneratedDocument {
        document_id: request.id,
        content,
        variables,
        entity_links,
        sections,
        generated_at: Utc::now(),
    })
}

/// Resolve template variables from multiple sources
///
/// Variable source priority:
/// 1. UserInput (direct from request)
/// 2. KnowledgeGraph (from entity queries)
/// 3. AgentGenerated (AI-generated content)
/// 4. Default (template default values)
fn resolve_variables(
    request: &DocumentRequest,
    research: &ResearchContext,
    template: &Template,
) -> Result<Vec<TemplateVariable>, AgentError> {
    let mut resolved_vars = Vec::new();

    // Track which variables have been resolved
    let mut resolved_names = HashMap::new();

    // Priority 1: User input (highest priority)
    for (key, value) in &request.context {
        resolved_names.insert(key.clone(), true);
        resolved_vars.push(TemplateVariable {
            name: key.clone(),
            value: value.clone(),
            source: VariableSource::UserInput,
        });
    }

    // Priority 2: Knowledge Graph (from research suggestions)
    for suggestion in &research.suggested_variables {
        if !resolved_names.contains_key(&suggestion.name) {
            if let Some(value) = &suggestion.suggested_value {
                resolved_names.insert(suggestion.name.clone(), true);
                resolved_vars.push(TemplateVariable {
                    name: suggestion.name.clone(),
                    value: value.clone(),
                    source: VariableSource::KnowledgeGraph,
                });
            }
        }
    }

    // Priority 3: Check for any remaining required variables
    // For now, we'll error if required variables are missing
    // In the future, AI generation could fill these in
    for var_name in &template.required_variables {
        if !resolved_names.contains_key(var_name) {
            return Err(AgentError::TemplateError(format!(
                "Required variable missing: {}",
                var_name
            )));
        }
    }

    Ok(resolved_vars)
}

/// Build Tera context from resolved variables
fn build_template_context(variables: &[TemplateVariable]) -> HashMap<String, String> {
    let mut context = HashMap::new();
    for var in variables {
        context.insert(var.name.clone(), var.value.clone());
    }
    context
}

/// Convert Vec<TemplateVariable> to HashMap for template engine
fn variables_to_map(variables: &[TemplateVariable]) -> HashMap<String, TemplateVariable> {
    let mut map = HashMap::new();
    for var in variables {
        map.insert(var.name.clone(), var.clone());
    }
    map
}

/// Add conditional section flags to context
fn add_conditional_sections(
    context: &mut HashMap<String, String>,
    research: &ResearchContext,
    template: &Template,
) {
    // Set flags for conditional sections based on research context
    // Optional sections become include_<section_name> flags
    for section_name in &template.optional_sections {
        // Include optional sections if they were suggested by research
        let should_include = research.suggested_sections.contains(section_name);
        context.insert(format!("include_{}", section_name), should_include.to_string());
    }

    // Add mandatory section flags
    for section_name in &research.mandatory_sections {
        context.insert(format!("has_{}", section_name), "true".to_string());
    }
}

/// Generate AI-powered content sections
///
/// TODO: This is a stub. Actual AI generation will be implemented
/// when the AI provider infrastructure is available.
async fn generate_ai_sections(
    context: &mut HashMap<String, String>,
    research: &ResearchContext,
    _config: &ContentAgentConfig,
) -> Result<(), AgentError> {
    // Generate standard sections like summary, background, etc.
    let sections_to_generate = vec![
        ("introduction", "Introductie"),
        ("background", "Achtergrond"),
        ("conclusion", "Conclusie"),
    ];

    for (section_key, section_name) in sections_to_generate {
        if !context.contains_key(section_key) {
            // Generate placeholder content
            let content = format!(
                "[{}] Tekst voor {} document in domein {}.",
                section_name,
                research.document_type,
                research.domain_context.domain_id
            );
            context.insert(section_key.to_string(), content);
        }
    }

    Ok(())
}

/// Extract metadata about document sections
fn extract_section_metadata(
    content: &str,
    template: &Template,
) -> Vec<SectionMetadata> {
    let mut sections = Vec::new();

    // Parse markdown headers to find sections
    for line in content.lines() {
        if let Some(rest) = line.strip_prefix('#') {
            // Strip any additional # symbols for subheadings
            let name = rest.trim_start_matches('#').trim().to_string();
            let is_optional = template.optional_sections.iter()
                .any(|s| name.to_lowercase().contains(&s.to_lowercase()));
            sections.push(SectionMetadata {
                name: name.clone(),
                rendered: true,
                length: 0,  // Would require more parsing
                ai_generated: is_optional,
            });
        }
    }

    // If no sections found, add a default
    if sections.is_empty() {
        sections.push(SectionMetadata {
            name: "content".to_string(),
            rendered: true,
            length: content.len(),
            ai_generated: false,
        });
    }

    sections
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashMap;

    fn create_test_request() -> DocumentRequest {
        let mut context = HashMap::new();
        context.insert("reference_number".to_string(), "TEST-001".to_string());
        context.insert("requester".to_string(), "Test User".to_string());

        DocumentRequest {
            id: Uuid::new_v4(),
            domain_id: "test-domain".to_string(),
            document_type: "woo_besluit".to_string(),
            context,
            requested_at: Utc::now(),
        }
    }

    fn create_test_research_context() -> ResearchContext {
        ResearchContext {
            document_type: "woo_besluit".to_string(),
            domain_context: crate::agents::research::DomainContext {
                domain_id: "test-domain".to_string(),
                domain_name: "Test Domain".to_string(),
                organizational_unit: None,
                applicable_regulations: vec!["Woo".to_string()],
                standard_procedures: vec![],
            },
            mandatory_sections: vec![
                "header".to_string(),
                "decision".to_string(),
            ],
            optional_sections: vec![
                "background".to_string(),
                "attachments".to_string(),
            ],
            suggested_sections: vec![
                "background".to_string(),  // Suggest including background
            ],
            similar_documents: vec![],
            related_entities: vec![],
            provisa_guidelines: vec![],
            suggested_variables: vec![
                crate::agents::research::TemplateVariableSuggestion {
                    name: "organization".to_string(),
                    suggested_value: Some("Gemeente Test".to_string()),
                    source: iou_core::document::VariableSource::KnowledgeGraph,
                    is_required: true,
                },
            ],
            timestamp: Utc::now(),
        }
    }

    fn create_test_template() -> Template {
        Template {
            id: "test-template".to_string(),
            name: "Test Template".to_string(),
            domain_id: "test-domain".to_string(),
            document_type: "woo_besluit".to_string(),
            content: "# {{ reference_number }}\n\nAanvraag van: {{ requester }}".to_string(),
            required_variables: vec!["reference_number".to_string(), "requester".to_string()],
            optional_sections: vec!["background".to_string()],
            version: 1,
            created_at: Utc::now(),
            updated_at: Utc::now(),
            is_active: true,
        }
    }

    fn create_template_engine() -> TemplateEngine {
        TemplateEngine::new().unwrap()
    }

    fn create_kg_client() -> KnowledgeGraph {
        KnowledgeGraph::new()
    }

    #[test]
    fn test_content_config_default() {
        let config = ContentAgentConfig::default();
        assert_eq!(config.max_section_length, 5000);
        assert_eq!(config.enable_entity_linking, true);
        assert_eq!(config.default_language, "nl");
        assert!(!config.enable_ai_generation);
    }

    #[test]
    fn test_entity_link() {
        let link = EntityLink {
            entity_id: "ORG-001".to_string(),
            display_text: "Gemeente Utrecht".to_string(),
            entity_type: "Organization".to_string(),
            position: 100,
        };

        assert_eq!(link.entity_type, "Organization");
        assert_eq!(link.position, 100);
    }

    #[test]
    fn test_section_metadata() {
        let meta = SectionMetadata {
            name: "introduction".to_string(),
            rendered: true,
            length: 500,
            ai_generated: false,
        };

        assert!(meta.rendered);
        assert!(!meta.ai_generated);
        assert_eq!(meta.length, 500);
    }

    #[test]
    fn test_resolve_variables_from_user_input() {
        let request = create_test_request();
        // Create research context without KG suggestions
        let mut research = create_test_research_context();
        research.suggested_variables.clear();

        let template = Template {
            id: "test".to_string(),
            name: "Test".to_string(),
            domain_id: "test".to_string(),
            document_type: "test".to_string(),
            content: String::new(),
            required_variables: vec![
                "reference_number".to_string(),
                "requester".to_string(),
            ],
            optional_sections: vec![],
            version: 1,
            created_at: Utc::now(),
            updated_at: Utc::now(),
            is_active: true,
        };

        let result = resolve_variables(&request, &research, &template);

        assert!(result.is_ok());
        let variables = result.unwrap();
        assert_eq!(variables.len(), 2);

        // Verify user input source
        assert!(variables.iter().any(|v|
            v.name == "reference_number" &&
            v.value == "TEST-001" &&
            matches!(v.source, VariableSource::UserInput)
        ));
    }

    #[test]
    fn test_resolve_variables_from_knowledge_graph() {
        let mut context = HashMap::new();
        context.insert("reference_number".to_string(), "TEST-001".to_string());

        let request = DocumentRequest {
            id: Uuid::new_v4(),
            domain_id: "test-domain".to_string(),
            document_type: "woo_besluit".to_string(),
            context,
            requested_at: Utc::now(),
        };

        let research = create_test_research_context();

        let template = Template {
            id: "test".to_string(),
            name: "Test".to_string(),
            domain_id: "test".to_string(),
            document_type: "test".to_string(),
            content: String::new(),
            required_variables: vec![
                "reference_number".to_string(),
                "organization".to_string(),  // From KG suggestions
            ],
            optional_sections: vec![],
            version: 1,
            created_at: Utc::now(),
            updated_at: Utc::now(),
            is_active: true,
        };

        let result = resolve_variables(&request, &research, &template);

        assert!(result.is_ok());
        let variables = result.unwrap();

        // Should have user input + KG suggestion
        assert!(variables.iter().any(|v|
            v.name == "organization" &&
            v.value == "Gemeente Test" &&
            matches!(v.source, VariableSource::KnowledgeGraph)
        ));
    }

    #[test]
    fn test_resolve_variables_missing_required() {
        let request = create_test_request();
        let research = create_test_research_context();

        let template = Template {
            id: "test".to_string(),
            name: "Test".to_string(),
            domain_id: "test".to_string(),
            document_type: "test".to_string(),
            content: String::new(),
            required_variables: vec![
                "reference_number".to_string(),
                "missing_var".to_string(),  // Not available anywhere
            ],
            optional_sections: vec![],
            version: 1,
            created_at: Utc::now(),
            updated_at: Utc::now(),
            is_active: true,
        };

        let result = resolve_variables(&request, &research, &template);

        assert!(result.is_err());
    }

    #[test]
    fn test_add_conditional_sections() {
        let research = create_test_research_context();
        let template = Template {
            id: "test".to_string(),
            name: "Test".to_string(),
            domain_id: "test".to_string(),
            document_type: "test".to_string(),
            content: String::new(),
            required_variables: vec![],
            optional_sections: vec!["background".to_string(), "attachments".to_string()],
            version: 1,
            created_at: Utc::now(),
            updated_at: Utc::now(),
            is_active: true,
        };

        let mut context = HashMap::new();
        add_conditional_sections(&mut context, &research, &template);

        // Background is in optional_sections, so include_background should be true
        assert_eq!(context.get("include_background"), Some(&"true".to_string()));
    }

    #[test]
    fn test_extract_section_metadata() {
        let content = r#"
# Introduction
This is the introduction.

# Decision
This is the decision section.

## Details
Subsection details.
"#;

        let template = Template {
            id: "test".to_string(),
            name: "Test".to_string(),
            domain_id: "test".to_string(),
            document_type: "test".to_string(),
            content: String::new(),
            required_variables: vec![],
            optional_sections: vec!["background".to_string()],
            version: 1,
            created_at: Utc::now(),
            updated_at: Utc::now(),
            is_active: true,
        };

        let sections = extract_section_metadata(content, &template);

        assert_eq!(sections.len(), 3);
        assert_eq!(sections[0].name, "Introduction");
        assert_eq!(sections[1].name, "Decision");
        assert_eq!(sections[2].name, "Details");
    }

    #[tokio::test]
    async fn test_execute_content_agent_renders_template() {
        let request = create_test_request();
        let mut research = create_test_research_context();
        research.suggested_variables.clear();  // Clear KG suggestions for this test
        let template = create_test_template();
        let kg = create_kg_client();
        let engine = create_template_engine();

        // Register the template
        engine.register_template(&template.id, &template.content).unwrap();

        let result = execute_content_agent(&request, &research, &template, &kg, &engine).await;

        assert!(result.is_ok());
        let doc = result.unwrap();

        assert!(!doc.content.is_empty());
        assert!(doc.content.contains("TEST-001"));
        assert!(doc.content.contains("Test User"));
        assert_eq!(doc.variables.len(), 2);
    }

    #[tokio::test]
    async fn test_execute_content_agent_handles_missing_variables() {
        let request = create_test_request();
        let research = create_test_research_context();

        // Template requires a variable that's not available
        let template = Template {
            id: "missing-var-template".to_string(),
            name: "Missing Var Template".to_string(),
            domain_id: "test-domain".to_string(),
            document_type: "woo_besluit".to_string(),
            content: "{{ missing_var }}".to_string(),
            required_variables: vec!["missing_var".to_string()],
            optional_sections: vec![],
            version: 1,
            created_at: Utc::now(),
            updated_at: Utc::now(),
            is_active: true,
        };

        let kg = create_kg_client();
        let engine = create_template_engine();

        let result = execute_content_agent(&request, &research, &template, &kg, &engine).await;

        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_execute_content_agent_includes_kg_suggestions() {
        let mut context = HashMap::new();
        context.insert("reference_number".to_string(), "TEST-001".to_string());

        let request = DocumentRequest {
            id: Uuid::new_v4(),
            domain_id: "test-domain".to_string(),
            document_type: "woo_besluit".to_string(),
            context,
            requested_at: Utc::now(),
        };

        let research = create_test_research_context();

        let template = Template {
            id: "kg-template".to_string(),
            name: "KG Template".to_string(),
            domain_id: "test-domain".to_string(),
            document_type: "woo_besluit".to_string(),
            content: "{{ reference_number }} - {{ organization }}".to_string(),
            required_variables: vec!["reference_number".to_string(), "organization".to_string()],
            optional_sections: vec![],
            version: 1,
            created_at: Utc::now(),
            updated_at: Utc::now(),
            is_active: true,
        };

        let kg = create_kg_client();
        let engine = create_template_engine();
        engine.register_template(&template.id, &template.content).unwrap();

        let result = execute_content_agent(&request, &research, &template, &kg, &engine).await;

        assert!(result.is_ok());
        let doc = result.unwrap();

        // Should include KG suggestion for organization
        assert!(doc.content.contains("Gemeente Test"));
    }
}
